var translations = {
  en: {
    language: "Language",
    play: "Play",
    instructions: "Instructions",
    credits: "Credits",
    select_lander: "Select your lander",
    classic_info: "Fuel: 1000<br />Mass: 1000<br />Main thrust: 6<br />Side thrust: 3<br />Good: Balanced and reliable<br />Bad: No standout strengths",
    round_info: "Fuel: 1200<br />Mass: 1100<br />Main thrust: 5.5<br />Side thrust: 2.5<br />Good: Long endurance<br />Bad: Not very responsive",
    triangle_info: "Fuel: 800<br />Mass: 900<br />Main thrust: 7<br />Side thrust: 4<br />Good: Very agile<br />Bad: Limited fuel",
    restart: "Restart",
    share: "Share Stats",
    instructions_paragraph: "Use the arrow keys (↑ for the main engine, ← and → for the side thrusters) or the on‑screen buttons above on mobile devices. Land softly on the <span class=\"landing-pad\">green landing pad</span>! Each time you land successfully you advance to the next level, which increases gravity and reduces your starting fuel.",
    instructions_modal_title: "Instructions",
    instructions_modal_body: "Use the arrow keys to control the module: ↑ for the main engine, ← and → for the side thrusters. On mobile devices you can use the on-screen buttons. Land softly on the <span class=\"landing-pad\">green landing pad</span>! Each time you land successfully you advance to the next level, which increases gravity and reduces your starting fuel.",
    close_instructions: "Close",
    credits_modal_title: "Credits",
    credits_modal_body: "This game was created entirely by a large language model, specifically <strong>ChatGPT</strong>, on behalf of the user Andrea. All code and content were generated by the AI, with the supervision of the user.",
    close_credits: "Close",
    classic_aria: "Classic lander",
    round_aria: "Round lander",
    triangle_aria: "Triangular lander",
    success_message: "Successful landing!",
    crash_message: "Crash!",
    next_level: "Next Level",
    retry_level: "Retry Level"
  },
  it: {
    language: "Lingua",
    play: "Gioca",
    instructions: "Istruzioni",
    credits: "Crediti",
    select_lander: "Seleziona il tuo lander",
    classic_info: "Carburante: 1000<br />Massa: 1000<br />Spinta principale: 6<br />Spinta laterale: 3<br />Qualità: Equilibrato e affidabile<br />Difetti: Nessun punto di forza",
    round_info: "Carburante: 1200<br />Massa: 1100<br />Spinta principale: 5.5<br />Spinta laterale: 2.5<br />Qualità: Grande autonomia<br />Difetti: Poco reattivo",
    triangle_info: "Carburante: 800<br />Massa: 900<br />Spinta principale: 7<br />Spinta laterale: 4<br />Qualità: Molto agile<br />Difetti: Carburante limitato",
    restart: "Ricomincia",
    share: "Condividi statistiche",
    instructions_paragraph: "Usa le frecce della tastiera (↑ per il motore principale, ← e → per i propulsori laterali) oppure i pulsanti sullo schermo sopra nei dispositivi mobili. Atterra dolcemente sulla <span class=\"landing-pad\">piattaforma verde</span>! Ogni volta che atterri con successo avanzi al livello successivo, che aumenta la gravità e riduce il carburante iniziale.",
    instructions_modal_title: "Istruzioni",
    instructions_modal_body: "Usa le frecce della tastiera per controllare il modulo: ↑ per accendere il motore principale, ← e → per i propulsori laterali. Sui dispositivi mobili puoi usare i pulsanti sullo schermo. Atterra dolcemente sulla <span class=\"landing-pad\">piattaforma verde</span>! Ogni volta che atterri con successo avanzi al livello successivo, che aumenta la gravità e riduce il carburante.",
    close_instructions: "Chiudi",
    credits_modal_title: "Crediti",
    credits_modal_body: "Questo gioco è stato creato interamente da un modello di linguaggio di grandi dimensioni, nello specifico <strong>ChatGPT</strong>, per conto dell'utente Andrea. Tutto il codice e i contenuti sono stati generati dall'AI, con la supervisione dell'utente.",
    close_credits: "Chiudi",
    classic_aria: "Lander classico",
    round_aria: "Lander rotondo",
    triangle_aria: "Lander triangolare",
    success_message: "Atterraggio riuscito!",
    crash_message: "Schianto!",
    next_level: "Livello successivo",
    retry_level: "Riprova livello"
  },
  de: {
    language: "Sprache",
    play: "Spielen",
    instructions: "Anleitung",
    credits: "Credits",
    select_lander: "W\u00e4hle deinen Lander",
    classic_info: "Treibstoff: 1000<br />Masse: 1000<br />Hauptschub: 6<br />Seitenschub: 3<br />Vorteil: Ausgewogen und zuverl\u00e4ssig<br />Nachteil: Keine besonderen St\u00e4rken",
    round_info: "Treibstoff: 1200<br />Masse: 1100<br />Hauptschub: 5,5<br />Seitenschub: 2,5<br />Vorteil: Gro\u00dfe Reichweite<br />Nachteil: Wenig reaktionsschnell",
    triangle_info: "Treibstoff: 800<br />Masse: 900<br />Hauptschub: 7<br />Seitenschub: 4<br />Vorteil: Sehr agil<br />Nachteil: Begrenzter Treibstoff",
    restart: "Neustart",
    share: "Statistiken teilen",
    instructions_paragraph: "Benutze die Pfeiltasten (↑ f\u00fcr den Hauptantrieb, ← und → f\u00fcr die Seitentriebwerke) oder die oben angezeigten Bildschirmtasten auf mobilen Ger\u00e4ten. Lande sanft auf der <span class=\"landing-pad\">gr\u00fcnen Landeplattform</span>! Jedes Mal, wenn du erfolgreich landest, steigst du zum n\u00e4chsten Level auf, wodurch die Schwerkraft erh\u00f6ht und dein Starttreibstoff reduziert wird.",
    instructions_modal_title: "Anleitung",
    instructions_modal_body: "Benutze die Pfeiltasten, um das Modul zu steuern: ↑ f\u00fcr den Hauptantrieb, ← und → f\u00fcr die Seitentriebwerke. Auf mobilen Ger\u00e4ten kannst du die Bildschirmtasten verwenden. Lande sanft auf der <span class=\"landing-pad\">gr\u00fcnen Landeplattform</span>! Jedes Mal, wenn du erfolgreich landest, steigst du zum n\u00e4chsten Level auf, wodurch die Schwerkraft erh\u00f6ht und dein Starttreibstoff reduziert wird.",
    close_instructions: "Schlie\u00dfen",
    credits_modal_title: "Credits",
    credits_modal_body: "Dieses Spiel wurde vollst\u00e4ndig von einem gro\u00dfen Sprachmodell erstellt, n\u00e4mlich <strong>ChatGPT</strong>, im Auftrag des Benutzers Andrea. Der gesamte Code und Inhalt wurden von der KI mit Aufsicht des Benutzers generiert.",
    close_credits: "Schlie\u00dfen",
    classic_aria: "Klassischer Lander",
    round_aria: "Runder Lander",
    triangle_aria: "Dreieckiger Lander",
    success_message: "Erfolgreiche Landung!",
    crash_message: "Absturz!",
    next_level: "N\u00e4chstes Level",
    retry_level: "Level wiederholen"
  }
};

var currentLang = 'en';

function setLanguage(lang) {
  currentLang = lang;
  document.documentElement.lang = lang;
  var elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    var translation = translations[lang][key];
    if (translation) {
      el.innerHTML = translation;
    }
  });
  var ariaElements = document.querySelectorAll('[data-i18n-aria-label]');
  ariaElements.forEach(function(el) {
    var key = el.getAttribute('data-i18n-aria-label');
    var translation = translations[lang][key];
    if (translation) {
      el.setAttribute('aria-label', translation);
    }
  });
  if (window.game && typeof window.game.updateUI === 'function') {
    window.game.updateUI();
  }
}

var languageSelect = document.getElementById('languageSelect');
if (languageSelect) {
  languageSelect.addEventListener('change', function(e) {
    setLanguage(e.target.value);
  });
}

setLanguage(currentLang);
