var translations = {
  en: {
    language: "Language",
    play: "Play",
    instructions: "Instructions",
    credits: "Credits",
    select_lander: "Select your lander",
    classic_info: "Fuel: 1000<br />Mass: 1000<br />Main thrust: 6<br />Side thrust: 3<br />Good: Balanced and reliable<br />Bad: No standout strengths",
    round_info: "Fuel: 1200<br />Mass: 1100<br />Main thrust: 5.5<br />Side thrust: 2.5<br />Good: Long endurance<br />Bad: Not very responsive",
    triangle_info: "Fuel: 800<br />Mass: 900<br />Main thrust: 7<br />Side thrust: 4<br />Good: Very agile<br />Bad: Limited fuel",
    restart: "Restart",
    share: "Share Stats",
    instructions_paragraph: "Use the arrow keys (↑ for the main engine, ← and → for the side thrusters) or the on‑screen buttons above on mobile devices. Land softly on the <span class=\"landing-pad\">green landing pad</span>! Each time you land successfully you advance to the next level. Early levels increase gravity and reduce your starting fuel, while later levels keep gravity steady but introduce tougher terrain.",
    instructions_modal_title: "Instructions",
    instructions_modal_body: "Use the arrow keys to control the module: ↑ for the main engine, ← and → for the side thrusters. On mobile devices you can use the on-screen buttons. Land softly on the <span class=\"landing-pad\">green landing pad</span>! Each time you land successfully you advance to the next level. Early levels increase gravity and reduce your starting fuel, while later levels keep gravity steady but introduce tougher terrain.",
    close_instructions: "Close",
    credits_modal_title: "Credits",
    credits_modal_body: "This game was created entirely by a large language model, specifically <strong>ChatGPT</strong>, on behalf of the user Andrea. All code and content were generated by the AI, with the supervision of the user.",
    close_credits: "Close",
    classic_aria: "Classic lander",
    round_aria: "Round lander",
    triangle_aria: "Triangular lander",
    success_message: "Successful landing!",
    crash_message: "Crash!",
    next_level: "Next Level",
    retry_level: "Retry Level"
  },
  it: {
    language: "Lingua",
    play: "Gioca",
    instructions: "Istruzioni",
    credits: "Crediti",
    select_lander: "Seleziona il tuo lander",
    classic_info: "Carburante: 1000<br />Massa: 1000<br />Spinta principale: 6<br />Spinta laterale: 3<br />Qualità: Equilibrato e affidabile<br />Difetti: Nessun punto di forza",
    round_info: "Carburante: 1200<br />Massa: 1100<br />Spinta principale: 5.5<br />Spinta laterale: 2.5<br />Qualità: Grande autonomia<br />Difetti: Poco reattivo",
    triangle_info: "Carburante: 800<br />Massa: 900<br />Spinta principale: 7<br />Spinta laterale: 4<br />Qualità: Molto agile<br />Difetti: Carburante limitato",
    restart: "Ricomincia",
    share: "Condividi statistiche",
    instructions_paragraph: "Usa le frecce della tastiera (↑ per il motore principale, ← e → per i propulsori laterali) oppure i pulsanti sullo schermo sopra nei dispositivi mobili. Atterra dolcemente sulla <span class=\"landing-pad\">piattaforma verde</span>! Ogni volta che atterri con successo avanzi al livello successivo. Nei primi livelli la gravità aumenta e il carburante iniziale diminuisce, mentre più avanti la gravità resta simile ma il terreno diventa più impegnativo.",
    instructions_modal_title: "Istruzioni",
    instructions_modal_body: "Usa le frecce della tastiera per controllare il modulo: ↑ per accendere il motore principale, ← e → per i propulsori laterali. Sui dispositivi mobili puoi usare i pulsanti sullo schermo. Atterra dolcemente sulla <span class=\"landing-pad\">piattaforma verde</span>! Ogni volta che atterri con successo avanzi al livello successivo. Nei primi livelli la gravità aumenta e il carburante iniziale diminuisce, mentre più avanti la gravità resta simile ma il terreno diventa più impegnativo.",
    close_instructions: "Chiudi",
    credits_modal_title: "Crediti",
    credits_modal_body: "Questo gioco è stato creato interamente da un modello di linguaggio di grandi dimensioni, nello specifico <strong>ChatGPT</strong>, per conto dell'utente Andrea. Tutto il codice e i contenuti sono stati generati dall'AI, con la supervisione dell'utente.",
    close_credits: "Chiudi",
    classic_aria: "Lander classico",
    round_aria: "Lander rotondo",
    triangle_aria: "Lander triangolare",
    success_message: "Atterraggio riuscito!",
    crash_message: "Schianto!",
    next_level: "Livello successivo",
    retry_level: "Riprova livello"
  },
  de: {
    language: "Sprache",
    play: "Spielen",
    instructions: "Anleitung",
    credits: "Credits",
    select_lander: "W\u00e4hle deinen Lander",
    classic_info: "Treibstoff: 1000<br />Masse: 1000<br />Hauptschub: 6<br />Seitenschub: 3<br />Vorteil: Ausgewogen und zuverl\u00e4ssig<br />Nachteil: Keine besonderen St\u00e4rken",
    round_info: "Treibstoff: 1200<br />Masse: 1100<br />Hauptschub: 5,5<br />Seitenschub: 2,5<br />Vorteil: Gro\u00dfe Reichweite<br />Nachteil: Wenig reaktionsschnell",
    triangle_info: "Treibstoff: 800<br />Masse: 900<br />Hauptschub: 7<br />Seitenschub: 4<br />Vorteil: Sehr agil<br />Nachteil: Begrenzter Treibstoff",
    restart: "Neustart",
    share: "Statistiken teilen",
    instructions_paragraph: "Benutze die Pfeiltasten (↑ f\u00fcr den Hauptantrieb, ← und → f\u00fcr die Seitentriebwerke) oder die oben angezeigten Bildschirmtasten auf mobilen Ger\u00e4ten. Lande sanft auf der <span class=\"landing-pad\">gr\u00fcnen Landeplattform</span>! Jedes Mal, wenn du erfolgreich landest, steigst du zum n\u00e4chsten Level auf. In den ersten Leveln erh\u00f6ht sich die Schwerkraft und dein Starttreibstoff wird reduziert, sp\u00e4ter bleibt die Schwerkraft \u00e4hnlich, aber das Gel\u00e4nde wird anspruchsvoller.",
    instructions_modal_title: "Anleitung",
    instructions_modal_body: "Benutze die Pfeiltasten, um das Modul zu steuern: ↑ f\u00fcr den Hauptantrieb, ← und → f\u00fcr die Seitentriebwerke. Auf mobilen Ger\u00e4ten kannst du die Bildschirmtasten verwenden. Lande sanft auf der <span class=\"landing-pad\">gr\u00fcnen Landeplattform</span>! Jedes Mal, wenn du erfolgreich landest, steigst du zum n\u00e4chsten Level auf. In den ersten Leveln erh\u00f6ht sich die Schwerkraft und dein Starttreibstoff wird reduziert, sp\u00e4ter bleibt die Schwerkraft \u00e4hnlich, aber das Gel\u00e4nde wird anspruchsvoller.",
    close_instructions: "Schlie\u00dfen",
    credits_modal_title: "Credits",
    credits_modal_body: "Dieses Spiel wurde vollst\u00e4ndig von einem gro\u00dfen Sprachmodell erstellt, n\u00e4mlich <strong>ChatGPT</strong>, im Auftrag des Benutzers Andrea. Der gesamte Code und Inhalt wurden von der KI mit Aufsicht des Benutzers generiert.",
    close_credits: "Schlie\u00dfen",
    classic_aria: "Klassischer Lander",
    round_aria: "Runder Lander",
    triangle_aria: "Dreieckiger Lander",
    success_message: "Erfolgreiche Landung!",
    crash_message: "Absturz!",
    next_level: "N\u00e4chstes Level",
    retry_level: "Level wiederholen"
  },
  pl: {
    language: "J\u0119zyk",
    play: "Graj",
    instructions: "Instrukcje",
    credits: "Autorzy",
    select_lander: "Wybierz sw\u00f3j l\u0105downik",
    classic_info: "Paliwo: 1000<br />Masa: 1000<br />G\u0142\u00f3wna si\u0142a ci\u0105gu: 6<br />Boczna si\u0142a ci\u0105gu: 3<br />Zalety: Zr\u00f3wnowa\u017cony i niezawodny<br />Wady: Brak wyra\u017anych atut\u00f3w",
    round_info: "Paliwo: 1200<br />Masa: 1100<br />G\u0142\u00f3wna si\u0142a ci\u0105gu: 5.5<br />Boczna si\u0142a ci\u0105gu: 2.5<br />Zalety: D\u0142ugi zasi\u0119g<br />Wady: Ma\u0142o responsywny",
    triangle_info: "Paliwo: 800<br />Masa: 900<br />G\u0142\u00f3wna si\u0142a ci\u0105gu: 7<br />Boczna si\u0142a ci\u0105gu: 4<br />Zalety: Bardzo zwrotny<br />Wady: Ograniczone paliwo",
    restart: "Restartuj",
    share: "Udost\u0119pnij statystyki",
    instructions_paragraph: "U\u017cyj klawiszy strza\u0142ek (\u2191 dla g\u0142\u00f3wnego silnika, \u2190 i \u2192 dla bocznych silnik\u00f3w) lub przycisk\u00f3w na ekranie na urz\u0105dzeniach mobilnych. Wyl\u0105duj delikatnie na <span class=\\\"landing-pad\\\">zielonej platformie l\u0105dowania</span>! Za ka\u017cdym udanym l\u0105dowaniem przechodzisz do nast\u0119pnego poziomu, co zwi\u0119ksza grawitacj\u0119 i zmniejsza pocz\u0105tkowe paliwo.",
    instructions_modal_title: "Instrukcje",
    instructions_modal_body: "U\u017cyj klawiszy strza\u0142ek, aby sterowa\u0107 modu\u0142em: \u2191 dla g\u0142\u00f3wnego silnika, \u2190 i \u2192 dla bocznych silnik\u00f3w. Na urz\u0105dzeniach mobilnych mo\u017cesz u\u017cy\u0107 przycisk\u00f3w na ekranie. Wyl\u0105duj delikatnie na <span class=\\\"landing-pad\\\">zielonej platformie l\u0105dowania</span>! Za ka\u017cdym udanym l\u0105dowaniem przechodzisz do nast\u0119pnego poziomu, co zwi\u0119ksza grawitacj\u0119 i zmniejsza pocz\u0105tkowe paliwo.",
    close_instructions: "Zamknij",
    credits_modal_title: "Autorzy",
    credits_modal_body: "Ta gra zosta\u0142a stworzona w ca\u0142o\u015bci przez du\u017cy model j\u0119zykowy, konkretnie <strong>ChatGPT</strong>, na zlecenie u\u017cytkownika Andrea. Ca\u0142y kod i zawarto\u015b\u0107 zosta\u0142y wygenerowane przez AI pod nadzorem u\u017cytkownika.",
    close_credits: "Zamknij",
    classic_aria: "Klasyczny l\u0105downik",
    round_aria: "Okr\u0105g\u0142y l\u0105downik",
    triangle_aria: "Tr\u00f3jk\u0105tny l\u0105downik",
    success_message: "Udane l\u0105dowanie!",
    crash_message: "Katastrofa!",
    next_level: "Nast\u0119pny poziom",
    retry_level: "Powt\u00f3rz poziom"
  }
  ,
  zh: {
    language: "语言",
    play: "开始",
    instructions: "说明",
    credits: "鸣谢",
    select_lander: "选择你的着陆器",
    classic_info: "燃料: 1000<br />质量: 1000<br />主推力: 6<br />侧推力: 3<br />优点: 平衡且可靠<br />缺点: 无明显优势",
    round_info: "燃料: 1200<br />质量: 1100<br />主推力: 5.5<br />侧推力: 2.5<br />优点: 持久耐用<br />缺点: 响应较慢",
    triangle_info: "燃料: 800<br />质量: 900<br />主推力: 7<br />侧推力: 4<br />优点: 非常灵活<br />缺点: 燃料有限",
    restart: "重新开始",
    share: "分享统计",
    instructions_paragraph: "使用方向键（↑ 表示主引擎，← 和 → 表示侧推进器）或移动设备上的屏幕按钮。轻轻降落在<span class=\"landing-pad\">绿色着陆平台</span>上！每次成功着陆都会进入下一关，重力增加且初始燃料减少。",
    instructions_modal_title: "说明",
    instructions_modal_body: "使用方向键控制模块：↑ 为主引擎，← 和 → 为侧推进器。移动设备上可使用屏幕按钮。轻轻降落在<span class=\"landing-pad\">绿色着陆平台</span>上！每次成功着陆都会进入下一关，重力增加且初始燃料减少。",
    close_instructions: "关闭",
    credits_modal_title: "鸣谢",
    credits_modal_body: "本游戏完全由大型语言模型，具体为<strong>ChatGPT</strong>，代表用户 Andrea 创作。所有代码和内容均由 AI 生成，并由用户监督。",
    close_credits: "关闭",
    classic_aria: "经典着陆器",
    round_aria: "圆形着陆器",
    triangle_aria: "三角形着陆器",
    success_message: "成功着陆！",
    crash_message: "坠毁！",
    next_level: "下一关",
    retry_level: "重试关卡"
  }
};

var currentLang = 'en';

function setLanguage(lang) {
  currentLang = lang;
  document.documentElement.lang = lang;
  var elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    var translation = translations[lang][key];
    if (translation) {
      el.innerHTML = translation;
    }
  });
  var ariaElements = document.querySelectorAll('[data-i18n-aria-label]');
  ariaElements.forEach(function(el) {
    var key = el.getAttribute('data-i18n-aria-label');
    var translation = translations[lang][key];
    if (translation) {
      el.setAttribute('aria-label', translation);
    }
  });
  if (window.game && typeof window.game.updateUI === 'function') {
    window.game.updateUI();
  }
}

var languageSelect = document.getElementById('languageSelect');
if (languageSelect) {
  languageSelect.addEventListener('change', function(e) {
    setLanguage(e.target.value);
  });
}

setLanguage(currentLang);
