var translations = {
  en: {
    language: "Language",
    play: "Play",
    instructions: "Instructions",
    credits: "Credits",
    select_lander: "Select your lander",
    classic_info: "Fuel: 1000<br />Mass: 1000<br />Main thrust: 6<br />Side thrust: 3<br />Good: Balanced and reliable<br />Bad: No standout strengths",
    round_info: "Fuel: 1200<br />Mass: 1100<br />Main thrust: 5.5<br />Side thrust: 2.5<br />Good: Long endurance<br />Bad: Not very responsive",
    triangle_info: "Fuel: 800<br />Mass: 900<br />Main thrust: 7<br />Side thrust: 4<br />Good: Very agile<br />Bad: Limited fuel",
    restart: "Restart",
    share: "Share Stats",
    instructions_paragraph: "Use the arrow keys (↑ for the main engine, ← and → for the side thrusters) or the on‑screen buttons above on mobile devices. Land softly on the <span class=\"landing-pad\">green landing pad</span>! Each time you land successfully you advance to the next level. Early levels increase gravity and reduce your starting fuel, while later levels keep gravity steady but introduce tougher terrain.",
    instructions_modal_title: "Instructions",
    instructions_modal_body: "Use the arrow keys to control the module: ↑ for the main engine, ← and → for the side thrusters. On mobile devices you can use the on-screen buttons. Land softly on the <span class=\"landing-pad\">green landing pad</span>! Each time you land successfully you advance to the next level. Early levels increase gravity and reduce your starting fuel, while later levels keep gravity steady but introduce tougher terrain.",
    close_instructions: "Close",
    credits_modal_title: "Credits",
    credits_modal_body: "This game was created entirely by a large language model, specifically <strong>ChatGPT</strong>, on behalf of the user Andrea. All code and content were generated by the AI, with the supervision of the user.",
    close_credits: "Close",
    classic_aria: "Classic lander",
    round_aria: "Round lander",
    triangle_aria: "Triangular lander",
    success_message: "Successful landing!",
    crash_message: "Crash!",
    next_level: "Next Level",
    retry_level: "Retry Level"
  },
  it: {
    language: "Lingua",
    play: "Gioca",
    instructions: "Istruzioni",
    credits: "Crediti",
    select_lander: "Seleziona il tuo lander",
    classic_info: "Carburante: 1000<br />Massa: 1000<br />Spinta principale: 6<br />Spinta laterale: 3<br />Qualità: Equilibrato e affidabile<br />Difetti: Nessun punto di forza",
    round_info: "Carburante: 1200<br />Massa: 1100<br />Spinta principale: 5.5<br />Spinta laterale: 2.5<br />Qualità: Grande autonomia<br />Difetti: Poco reattivo",
    triangle_info: "Carburante: 800<br />Massa: 900<br />Spinta principale: 7<br />Spinta laterale: 4<br />Qualità: Molto agile<br />Difetti: Carburante limitato",
    restart: "Ricomincia",
    share: "Condividi statistiche",
    instructions_paragraph: "Usa le frecce della tastiera (↑ per il motore principale, ← e → per i propulsori laterali) oppure i pulsanti sullo schermo sopra nei dispositivi mobili. Atterra dolcemente sulla <span class=\"landing-pad\">piattaforma verde</span>! Ogni volta che atterri con successo avanzi al livello successivo. Nei primi livelli la gravità aumenta e il carburante iniziale diminuisce, mentre più avanti la gravità resta simile ma il terreno diventa più impegnativo.",
    instructions_modal_title: "Istruzioni",
    instructions_modal_body: "Usa le frecce della tastiera per controllare il modulo: ↑ per accendere il motore principale, ← e → per i propulsori laterali. Sui dispositivi mobili puoi usare i pulsanti sullo schermo. Atterra dolcemente sulla <span class=\"landing-pad\">piattaforma verde</span>! Ogni volta che atterri con successo avanzi al livello successivo. Nei primi livelli la gravità aumenta e il carburante iniziale diminuisce, mentre più avanti la gravità resta simile ma il terreno diventa più impegnativo.",
    close_instructions: "Chiudi",
    credits_modal_title: "Crediti",
    credits_modal_body: "Questo gioco è stato creato interamente da un modello di linguaggio di grandi dimensioni, nello specifico <strong>ChatGPT</strong>, per conto dell'utente Andrea. Tutto il codice e i contenuti sono stati generati dall'AI, con la supervisione dell'utente.",
    close_credits: "Chiudi",
    classic_aria: "Lander classico",
    round_aria: "Lander rotondo",
    triangle_aria: "Lander triangolare",
    success_message: "Atterraggio riuscito!",
    crash_message: "Schianto!",
    next_level: "Livello successivo",
    retry_level: "Riprova livello"
  },
  de: {
    language: "Sprache",
    play: "Spielen",
    instructions: "Anleitung",
    credits: "Credits",
    select_lander: "W\u00e4hle deinen Lander",
    classic_info: "Treibstoff: 1000<br />Masse: 1000<br />Hauptschub: 6<br />Seitenschub: 3<br />Vorteil: Ausgewogen und zuverl\u00e4ssig<br />Nachteil: Keine besonderen St\u00e4rken",
    round_info: "Treibstoff: 1200<br />Masse: 1100<br />Hauptschub: 5,5<br />Seitenschub: 2,5<br />Vorteil: Gro\u00dfe Reichweite<br />Nachteil: Wenig reaktionsschnell",
    triangle_info: "Treibstoff: 800<br />Masse: 900<br />Hauptschub: 7<br />Seitenschub: 4<br />Vorteil: Sehr agil<br />Nachteil: Begrenzter Treibstoff",
    restart: "Neustart",
    share: "Statistiken teilen",
    instructions_paragraph: "Benutze die Pfeiltasten (↑ f\u00fcr den Hauptantrieb, ← und → f\u00fcr die Seitentriebwerke) oder die oben angezeigten Bildschirmtasten auf mobilen Ger\u00e4ten. Lande sanft auf der <span class=\"landing-pad\">gr\u00fcnen Landeplattform</span>! Jedes Mal, wenn du erfolgreich landest, steigst du zum n\u00e4chsten Level auf. In den ersten Leveln erh\u00f6ht sich die Schwerkraft und dein Starttreibstoff wird reduziert, sp\u00e4ter bleibt die Schwerkraft \u00e4hnlich, aber das Gel\u00e4nde wird anspruchsvoller.",
    instructions_modal_title: "Anleitung",
    instructions_modal_body: "Benutze die Pfeiltasten, um das Modul zu steuern: ↑ f\u00fcr den Hauptantrieb, ← und → f\u00fcr die Seitentriebwerke. Auf mobilen Ger\u00e4ten kannst du die Bildschirmtasten verwenden. Lande sanft auf der <span class=\"landing-pad\">gr\u00fcnen Landeplattform</span>! Jedes Mal, wenn du erfolgreich landest, steigst du zum n\u00e4chsten Level auf. In den ersten Leveln erh\u00f6ht sich die Schwerkraft und dein Starttreibstoff wird reduziert, sp\u00e4ter bleibt die Schwerkraft \u00e4hnlich, aber das Gel\u00e4nde wird anspruchsvoller.",
    close_instructions: "Schlie\u00dfen",
    credits_modal_title: "Credits",
    credits_modal_body: "Dieses Spiel wurde vollst\u00e4ndig von einem gro\u00dfen Sprachmodell erstellt, n\u00e4mlich <strong>ChatGPT</strong>, im Auftrag des Benutzers Andrea. Der gesamte Code und Inhalt wurden von der KI mit Aufsicht des Benutzers generiert.",
    close_credits: "Schlie\u00dfen",
    classic_aria: "Klassischer Lander",
    round_aria: "Runder Lander",
    triangle_aria: "Dreieckiger Lander",
    success_message: "Erfolgreiche Landung!",
    crash_message: "Absturz!",
    next_level: "N\u00e4chstes Level",
    retry_level: "Level wiederholen"
  },
  pl: {
    language: "J\u0119zyk",
    play: "Graj",
    instructions: "Instrukcje",
    credits: "Autorzy",
    select_lander: "Wybierz sw\u00f3j l\u0105downik",
    classic_info: "Paliwo: 1000<br />Masa: 1000<br />G\u0142\u00f3wna si\u0142a ci\u0105gu: 6<br />Boczna si\u0142a ci\u0105gu: 3<br />Zalety: Zr\u00f3wnowa\u017cony i niezawodny<br />Wady: Brak wyra\u017anych atut\u00f3w",
    round_info: "Paliwo: 1200<br />Masa: 1100<br />G\u0142\u00f3wna si\u0142a ci\u0105gu: 5.5<br />Boczna si\u0142a ci\u0105gu: 2.5<br />Zalety: D\u0142ugi zasi\u0119g<br />Wady: Ma\u0142o responsywny",
    triangle_info: "Paliwo: 800<br />Masa: 900<br />G\u0142\u00f3wna si\u0142a ci\u0105gu: 7<br />Boczna si\u0142a ci\u0105gu: 4<br />Zalety: Bardzo zwrotny<br />Wady: Ograniczone paliwo",
    restart: "Restartuj",
    share: "Udost\u0119pnij statystyki",
    instructions_paragraph: "U\u017cyj klawiszy strza\u0142ek (\u2191 dla g\u0142\u00f3wnego silnika, \u2190 i \u2192 dla bocznych silnik\u00f3w) lub przycisk\u00f3w na ekranie na urz\u0105dzeniach mobilnych. Wyl\u0105duj delikatnie na <span class=\\\"landing-pad\\\">zielonej platformie l\u0105dowania</span>! Za ka\u017cdym udanym l\u0105dowaniem przechodzisz do nast\u0119pnego poziomu, co zwi\u0119ksza grawitacj\u0119 i zmniejsza pocz\u0105tkowe paliwo.",
    instructions_modal_title: "Instrukcje",
    instructions_modal_body: "U\u017cyj klawiszy strza\u0142ek, aby sterowa\u0107 modu\u0142em: \u2191 dla g\u0142\u00f3wnego silnika, \u2190 i \u2192 dla bocznych silnik\u00f3w. Na urz\u0105dzeniach mobilnych mo\u017cesz u\u017cy\u0107 przycisk\u00f3w na ekranie. Wyl\u0105duj delikatnie na <span class=\\\"landing-pad\\\">zielonej platformie l\u0105dowania</span>! Za ka\u017cdym udanym l\u0105dowaniem przechodzisz do nast\u0119pnego poziomu, co zwi\u0119ksza grawitacj\u0119 i zmniejsza pocz\u0105tkowe paliwo.",
    close_instructions: "Zamknij",
    credits_modal_title: "Autorzy",
    credits_modal_body: "Ta gra zosta\u0142a stworzona w ca\u0142o\u015bci przez du\u017cy model j\u0119zykowy, konkretnie <strong>ChatGPT</strong>, na zlecenie u\u017cytkownika Andrea. Ca\u0142y kod i zawarto\u015b\u0107 zosta\u0142y wygenerowane przez AI pod nadzorem u\u017cytkownika.",
    close_credits: "Zamknij",
    classic_aria: "Klasyczny l\u0105downik",
    round_aria: "Okr\u0105g\u0142y l\u0105downik",
    triangle_aria: "Tr\u00f3jk\u0105tny l\u0105downik",
    success_message: "Udane l\u0105dowanie!",
    crash_message: "Katastrofa!",
    next_level: "Nast\u0119pny poziom",
    retry_level: "Powt\u00f3rz poziom"
  },
  zh: {
    language: "语言",
    play: "开始",
    instructions: "说明",
    credits: "鸣谢",
    select_lander: "选择你的着陆器",
    classic_info: "燃料: 1000<br />质量: 1000<br />主推力: 6<br />侧推力: 3<br />优点: 平衡且可靠<br />缺点: 无明显优势",
    round_info: "燃料: 1200<br />质量: 1100<br />主推力: 5.5<br />侧推力: 2.5<br />优点: 持久耐用<br />缺点: 响应较慢",
    triangle_info: "燃料: 800<br />质量: 900<br />主推力: 7<br />侧推力: 4<br />优点: 非常灵活<br />缺点: 燃料有限",
    restart: "重新开始",
    share: "分享统计",
    instructions_paragraph: "使用方向键（↑ 表示主引擎，← 和 → 表示侧推进器）或移动设备上的屏幕按钮。轻轻降落在<span class=\"landing-pad\">绿色着陆平台</span>上！每次成功着陆都会进入下一关，重力增加且初始燃料减少。",
    instructions_modal_title: "说明",
    instructions_modal_body: "使用方向键控制模块：↑ 为主引擎，← 和 → 为侧推进器。移动设备上可使用屏幕按钮。轻轻降落在<span class=\"landing-pad\">绿色着陆平台</span>上！每次成功着陆都会进入下一关，重力增加且初始燃料减少。",
    close_instructions: "关闭",
    credits_modal_title: "鸣谢",
    credits_modal_body: "本游戏完全由大型语言模型，具体为<strong>ChatGPT</strong>，代表用户 Andrea 创作。所有代码和内容均由 AI 生成，并由用户监督。",
    close_credits: "关闭",
    classic_aria: "经典着陆器",
    round_aria: "圆形着陆器",
    triangle_aria: "三角形着陆器",
    success_message: "成功着陆！",
    crash_message: "坠毁！",
    next_level: "下一关",
    retry_level: "重试关卡"
  },
  fa: {
    language: "زبان",
    play: "بازی",
    instructions: "دستورالعمل‌ها",
    credits: "سازندگان",
    select_lander: "فرودگر خود را انتخاب کنید",
    classic_info: "سوخت: ۱۰۰۰<br />جرم: ۱۰۰۰<br />پیشرانه اصلی: ۶<br />پیشرانه جانبی: ۳<br />خوب: متعادل و قابل اعتماد<br />بد: بدون نقطه قوت برجسته",
    round_info: "سوخت: ۱۲۰۰<br />جرم: ۱۱۰۰<br />پیشرانه اصلی: ۵٫۵<br />پیشرانه جانبی: ۲٫۵<br />خوب: ماندگاری زیاد<br />بد: واکنش‌پذیری کم",
    triangle_info: "سوخت: ۸۰۰<br />جرم: ۹۰۰<br />پیشرانه اصلی: ۷<br />پیشرانه جانبی: ۴<br />خوب: بسیار چابک<br />بد: سوخت محدود",
    restart: "شروع دوباره",
    share: "اشتراک‌گذاری آمار",
    instructions_paragraph: "از کلیدهای جهت‌نما استفاده کنید (↑ برای موتور اصلی، ← و → برای پیشرانه‌های جانبی) یا دکمه‌های روی صفحه در دستگاه‌های همراه. به‌آرامی روی <span class=\"landing-pad\">سکوی سبز فرود</span> بیایید! با هر فرود موفق به مرحله بعدی می‌روید. در مراحل اولیه گرانش افزایش می‌یابد و سوخت اولیه کاهش می‌یابد، در مراحل بعدی گرانش ثابت می‌ماند ولی زمین ناهموارتر می‌شود.",
    instructions_modal_title: "دستورالعمل‌ها",
    instructions_modal_body: "برای کنترل ماژول از کلیدهای جهت‌نما استفاده کنید: ↑ برای موتور اصلی، ← و → برای پیشرانه‌های جانبی. در دستگاه‌های همراه می‌توانید از دکمه‌های روی صفحه استفاده کنید. به‌آرامی روی <span class=\"landing-pad\">سکوی سبز فرود</span> بیایید! با هر فرود موفق به مرحله بعدی می‌روید. در مراحل اولیه گرانش افزایش می‌یابد و سوخت اولیه کاهش می‌یابد، در مراحل بعدی گرانش ثابت می‌ماند ولی زمین ناهموارتر می‌شود.",
    close_instructions: "بستن",
    credits_modal_title: "سازندگان",
    credits_modal_body: "این بازی به طور کامل توسط یک مدل زبانی بزرگ، یعنی <strong>ChatGPT</strong>، به نمایندگی از کاربر آندریا ساخته شده است. تمام کد و محتوا توسط هوش مصنوعی و با نظارت کاربر تولید شده‌اند.",
    close_credits: "بستن",
    classic_aria: "فرودگر کلاسیک",
    round_aria: "فرودگر گرد",
    triangle_aria: "فرودگر مثلثی",
    success_message: "فرود موفق!",
    crash_message: "سقوط!",
    next_level: "مرحله بعد",
    retry_level: "تلاش دوباره"
  },
  es: {
    language: "Idioma",
    play: "Jugar",
    instructions: "Instrucciones",
    credits: "Créditos",
    select_lander: "Selecciona tu módulo",
    classic_info: "Combustible: 1000<br />Masa: 1000<br />Impulso principal: 6<br />Impulso lateral: 3<br />Bueno: Equilibrado y confiable<br />Malo: Sin puntos fuertes destacados",
    round_info: "Combustible: 1200<br />Masa: 1100<br />Impulso principal: 5.5<br />Impulso lateral: 2.5<br />Bueno: Gran autonomía<br />Malo: Poco sensible",
    triangle_info: "Combustible: 800<br />Masa: 900<br />Impulso principal: 7<br />Impulso lateral: 4<br />Bueno: Muy ágil<br />Malo: Combustible limitado",
    restart: "Reiniciar",
    share: "Compartir estadísticas",
    instructions_paragraph: "Usa las flechas del teclado (↑ para el motor principal, ← y → para los propulsores laterales) o los botones en pantalla en dispositivos móviles. ¡Aterriza suavemente en la <span class=\"landing-pad\">plataforma verde</span>! Cada aterrizaje exitoso te lleva al siguiente nivel. En los primeros niveles la gravedad aumenta y el combustible inicial disminuye, mientras que más adelante la gravedad se mantiene pero el terreno se vuelve más difícil.",
    instructions_modal_title: "Instrucciones",
    instructions_modal_body: "Usa las flechas del teclado para controlar el módulo: ↑ para el motor principal, ← y → para los propulsores laterales. En dispositivos móviles puedes usar los botones en pantalla. ¡Aterriza suavemente en la <span class=\"landing-pad\">plataforma verde</span>! Cada aterrizaje exitoso te lleva al siguiente nivel. En los primeros niveles la gravedad aumenta y el combustible inicial disminuye, mientras que más adelante la gravedad se mantiene pero el terreno se vuelve más difícil.",
    close_instructions: "Cerrar",
    credits_modal_title: "Créditos",
    credits_modal_body: "Este juego fue creado completamente por un modelo de lenguaje grande, específicamente <strong>ChatGPT</strong>, en nombre del usuario Andrea. Todo el código y contenido fueron generados por la IA con la supervisión del usuario.",
    close_credits: "Cerrar",
    classic_aria: "Módulo clásico",
    round_aria: "Módulo redondo",
    triangle_aria: "Módulo triangular",
    success_message: "¡Aterrizaje exitoso!",
    crash_message: "¡Choque!",
    next_level: "Siguiente nivel",
    retry_level: "Reintentar nivel"
  },
  fr: {
    language: "Langue",
    play: "Jouer",
    instructions: "Instructions",
    credits: "Crédits",
    select_lander: "Sélectionnez votre module",
    classic_info: "Carburant : 1000<br />Masse : 1000<br />Poussée principale : 6<br />Poussée latérale : 3<br />Bon : Équilibré et fiable<br />Mauvais : Aucun point fort",
    round_info: "Carburant : 1200<br />Masse : 1100<br />Poussée principale : 5,5<br />Poussée latérale : 2,5<br />Bon : Grande autonomie<br />Mauvais : Peu réactif",
    triangle_info: "Carburant : 800<br />Masse : 900<br />Poussée principale : 7<br />Poussée latérale : 4<br />Bon : Très agile<br />Mauvais : Carburant limité",
    restart: "Recommencer",
    share: "Partager les statistiques",
    instructions_paragraph: "Utilisez les flèches du clavier (↑ pour le moteur principal, ← et → pour les propulseurs latéraux) ou les boutons à l'écran sur les appareils mobiles. Atterrissez doucement sur la <span class=\"landing-pad\">plateforme verte</span> ! Chaque atterrissage réussi vous fait passer au niveau suivant. Aux premiers niveaux, la gravité augmente et le carburant de départ diminue, tandis qu'aux niveaux suivants la gravité reste stable mais le terrain devient plus difficile.",
    instructions_modal_title: "Instructions",
    instructions_modal_body: "Utilisez les flèches du clavier pour contrôler le module : ↑ pour le moteur principal, ← et → pour les propulseurs latéraux. Sur les appareils mobiles, vous pouvez utiliser les boutons à l'écran. Atterrissez doucement sur la <span class=\"landing-pad\">plateforme verte</span> ! Chaque atterrissage réussi vous fait passer au niveau suivant. Aux premiers niveaux, la gravité augmente et le carburant de départ diminue, tandis qu'aux niveaux suivants la gravité reste stable mais le terrain devient plus difficile.",
    close_instructions: "Fermer",
    credits_modal_title: "Crédits",
    credits_modal_body: "Ce jeu a été entièrement créé par un grand modèle de langage, spécifiquement <strong>ChatGPT</strong>, pour le compte de l'utilisateur Andrea. Tout le code et le contenu ont été générés par l'IA avec la supervision de l'utilisateur.",
    close_credits: "Fermer",
    classic_aria: "Module classique",
    round_aria: "Module rond",
    triangle_aria: "Module triangulaire",
    success_message: "Atterrissage réussi !",
    crash_message: "Crash !",
    next_level: "Niveau suivant",
    retry_level: "Réessayer le niveau"
  },
  pt: {
    language: "Idioma",
    play: "Jogar",
    instructions: "Instruções",
    credits: "Créditos",
    select_lander: "Selecione seu módulo",
    classic_info: "Combustível: 1000<br />Massa: 1000<br />Empuxo principal: 6<br />Empuxo lateral: 3<br />Bom: Equilibrado e confiável<br />Ruim: Sem pontos fortes",
    round_info: "Combustível: 1200<br />Massa: 1100<br />Empuxo principal: 5,5<br />Empuxo lateral: 2,5<br />Bom: Grande autonomia<br />Ruim: Pouco responsivo",
    triangle_info: "Combustível: 800<br />Massa: 900<br />Empuxo principal: 7<br />Empuxo lateral: 4<br />Bom: Muito ágil<br />Ruim: Combustível limitado",
    restart: "Reiniciar",
    share: "Compartilhar estatísticas",
    instructions_paragraph: "Use as setas do teclado (↑ para o motor principal, ← e → para os propulsores laterais) ou os botões na tela em dispositivos móveis. Pouse suavemente na <span class=\"landing-pad\">plataforma verde</span>! Cada pouso bem-sucedido leva você ao próximo nível. Nos primeiros níveis, a gravidade aumenta e o combustível inicial diminui, enquanto nos níveis posteriores a gravidade permanece estável, mas o terreno fica mais difícil.",
    instructions_modal_title: "Instruções",
    instructions_modal_body: "Use as setas do teclado para controlar o módulo: ↑ para o motor principal, ← e → para os propulsores laterais. Em dispositivos móveis, você pode usar os botões na tela. Pouse suavemente na <span class=\"landing-pad\">plataforma verde</span>! Cada pouso bem-sucedido leva você ao próximo nível. Nos primeiros níveis, a gravidade aumenta e o combustível inicial diminui, enquanto nos níveis posteriores a gravidade permanece estável, mas o terreno fica mais difícil.",
    close_instructions: "Fechar",
    credits_modal_title: "Créditos",
    credits_modal_body: "Este jogo foi criado inteiramente por um grande modelo de linguagem, especificamente <strong>ChatGPT</strong>, em nome do usuário Andrea. Todo o código e conteúdo foram gerados pela IA com a supervisão do usuário.",
    close_credits: "Fechar",
    classic_aria: "Módulo clássico",
    round_aria: "Módulo redondo",
    triangle_aria: "Módulo triangular",
    success_message: "Pouso bem-sucedido!",
    crash_message: "Colisão!",
    next_level: "Próximo nível",
    retry_level: "Tentar novamente"
  },
  ru: {
    language: "Язык",
    play: "Играть",
    instructions: "Инструкции",
    credits: "Авторы",
    select_lander: "Выберите посадочный модуль",
    classic_info: "Топливо: 1000<br />Масса: 1000<br />Основная тяга: 6<br />Боковая тяга: 3<br />Плюс: Сбалансированный и надежный<br />Минус: Нет ярко выраженных преимуществ",
    round_info: "Топливо: 1200<br />Масса: 1100<br />Основная тяга: 5,5<br />Боковая тяга: 2,5<br />Плюс: Большая автономность<br />Минус: Низкая отзывчивость",
    triangle_info: "Топливо: 800<br />Масса: 900<br />Основная тяга: 7<br />Боковая тяга: 4<br />Плюс: Очень маневренный<br />Минус: Ограниченное топливо",
    restart: "Перезапуск",
    share: "Поделиться статистикой",
    instructions_paragraph: "Используйте клавиши со стрелками (↑ для главного двигателя, ← и → для боковых двигателей) или кнопки на экране на мобильных устройствах. Мягко приземляйтесь на <span class=\"landing-pad\">зелёную площадку</span>! Каждая удачная посадка переводит вас на следующий уровень. На ранних уровнях гравитация увеличивается и стартовое топливо уменьшается, а на последующих уровень гравитация остаётся прежней, но местность усложняется.",
    instructions_modal_title: "Инструкции",
    instructions_modal_body: "Используйте клавиши со стрелками для управления модулем: ↑ для главного двигателя, ← и → для боковых двигателей. На мобильных устройствах можно использовать кнопки на экране. Мягко приземляйтесь на <span class=\"landing-pad\">зелёную площадку</span>! Каждая удачная посадка переводит вас на следующий уровень. На ранних уровнях гравитация увеличивается и стартовое топливо уменьшается, а на последующих уровень гравитация остаётся прежней, но местность усложняется.",
    close_instructions: "Закрыть",
    credits_modal_title: "Авторы",
    credits_modal_body: "Эта игра полностью создана большим языковым моделем, а именно <strong>ChatGPT</strong>, по заказу пользователя Андреа. Весь код и контент были сгенерированы ИИ под наблюдением пользователя.",
    close_credits: "Закрыть",
    classic_aria: "Классический модуль",
    round_aria: "Круглый модуль",
    triangle_aria: "Треугольный модуль",
    success_message: "Успешная посадка!",
    crash_message: "Крушение!",
    next_level: "Следующий уровень",
    retry_level: "Повторить уровень"
  },
  ar: {
    language: "اللغة",
    play: "ابدأ",
    instructions: "التعليمات",
    credits: "الاعتمادات",
    select_lander: "اختر مركبتك",
    classic_info: "الوقود: 1000<br />الكتلة: 1000<br />الدفع الرئيسي: 6<br />الدفع الجانبي: 3<br />الجيد: متوازن وموثوق<br />السيئ: لا ميزات بارزة",
    round_info: "الوقود: 1200<br />الكتلة: 1100<br />الدفع الرئيسي: 5.5<br />الدفع الجانبي: 2.5<br />الجيد: مدى طويل<br />السيئ: استجابة ضعيفة",
    triangle_info: "الوقود: 800<br />الكتلة: 900<br />الدفع الرئيسي: 7<br />الدفع الجانبي: 4<br />الجيد: شديد الرشاقة<br />السيئ: وقود محدود",
    restart: "إعادة البدء",
    share: "مشاركة الإحصائيات",
    instructions_paragraph: "استخدم مفاتيح الأسهم (↑ للمحرك الرئيسي، ← و → للمحركات الجانبية) أو الأزرار على الشاشة في الأجهزة المحمولة. اهبط برفق على <span class=\"landing-pad\">المنصة الخضراء</span>! كل هبوط ناجح ينقلك إلى المستوى التالي. في المستويات الأولى تزداد الجاذبية ويقل الوقود الابتدائي، بينما في المستويات اللاحقة تبقى الجاذبية ثابتة لكن التضاريس تصبح أكثر صعوبة.",
    instructions_modal_title: "التعليمات",
    instructions_modal_body: "استخدم مفاتيح الأسهم للتحكم في المركبة: ↑ للمحرك الرئيسي، ← و → للمحركات الجانبية. على الأجهزة المحمولة يمكنك استخدام الأزرار على الشاشة. اهبط برفق على <span class=\"landing-pad\">المنصة الخضراء</span>! كل هبوط ناجح ينقلك إلى المستوى التالي. في المستويات الأولى تزداد الجاذبية ويقل الوقود الابتدائي، بينما في المستويات اللاحقة تبقى الجاذبية ثابتة لكن التضاريس تصبح أكثر صعوبة.",
    close_instructions: "إغلاق",
    credits_modal_title: "الاعتمادات",
    credits_modal_body: "تم إنشاء هذه اللعبة بالكامل بواسطة نموذج لغوي كبير، وهو <strong>ChatGPT</strong>، نيابةً عن المستخدم Andrea. تم إنشاء كل الشفرات والمحتوى بواسطة الذكاء الاصطناعي تحت إشراف المستخدم.",
    close_credits: "إغلاق",
    classic_aria: "مركبة كلاسيكية",
    round_aria: "مركبة دائرية",
    triangle_aria: "مركبة مثلثة",
    success_message: "هبوط ناجح!",
    crash_message: "تحطم!",
    next_level: "المستوى التالي",
    retry_level: "إعادة المحاولة"
  },
  ja: {
    language: "言語",
    play: "プレイ",
    instructions: "操作方法",
    credits: "クレジット",
    select_lander: "ランダーを選択",
    classic_info: "燃料: 1000<br />質量: 1000<br />主推力: 6<br />側推力: 3<br />長所: バランスが良く信頼性が高い<br />短所: 目立った長所なし",
    round_info: "燃料: 1200<br />質量: 1100<br />主推力: 5.5<br />側推力: 2.5<br />長所: 長時間稼働<br />短所: 反応が鈍い",
    triangle_info: "燃料: 800<br />質量: 900<br />主推力: 7<br />側推力: 4<br />長所: 非常に敏捷<br />短所: 燃料が少ない",
    restart: "リスタート",
    share: "統計を共有",
    instructions_paragraph: "矢印キー（↑はメインエンジン、←と→はサイドスラスター）またはモバイル端末では画面上のボタンを使用します。<span class=\"landing-pad\">緑の着陸パッド</span>にそっと着陸してください！着陸に成功するたびに次のレベルへ進みます。初期のレベルでは重力が増加し、初期燃料が減少します。後半のレベルでは重力は一定ですが、地形がより難しくなります.",
    instructions_modal_title: "操作方法",
    instructions_modal_body: "矢印キーを使ってモジュールを操作します: ↑でメインエンジン、←と→でサイドスラスター。モバイル端末では画面上のボタンも使用できます。<span class=\"landing-pad\">緑の着陸パッド</span>にそっと着陸してください！着陸に成功するたびに次のレベルへ進みます。初期のレベルでは重力が増加し、初期燃料が減少します。後半のレベルでは重力は一定ですが、地形がより難しくなります.",
    close_instructions: "閉じる",
    credits_modal_title: "クレジット",
    credits_modal_body: "このゲームは大規模言語モデル <strong>ChatGPT</strong> がユーザーAndreaのために完全に作成しました。すべてのコードとコンテンツはAIによって生成され、ユーザーの監督下にあります.",
    close_credits: "閉じる",
    classic_aria: "クラシックランダー",
    round_aria: "丸型ランダー",
    triangle_aria: "三角ランダー",
    success_message: "着陸成功！",
    crash_message: "クラッシュ！",
    next_level: "次のレベル",
    retry_level: "レベル再挑戦"
  },
  hi: {
    language: "भाषा",
    play: "खेलें",
    instructions: "निर्देश",
    credits: "श्रेय",
    select_lander: "अपना लैंडर चुनें",
    classic_info: "ईंधन: 1000<br />द्रव्यमान: 1000<br />मुख्य थ्रस्ट: 6<br />पार्श्व थ्रस्ट: 3<br />अच्छा: संतुलित और भरोसेमंद<br />खराब: कोई विशेष ताकत नहीं",
    round_info: "ईंधन: 1200<br />द्रव्यमान: 1100<br />मुख्य थ्रस्ट: 5.5<br />पार्श्व थ्रस्ट: 2.5<br />अच्छा: लंबी अवधि<br />खराब: बहुत प्रतिक्रियाशील नहीं",
    triangle_info: "ईंधन: 800<br />द्रव्यमान: 900<br />मुख्य थ्रस्ट: 7<br />पार्श्व थ्रस्ट: 4<br />अच्छा: बहुत चुस्त<br />खराब: सीमित ईंधन",
    restart: "पुनः प्रारंभ",
    share: "आंकड़े साझा करें",
    instructions_paragraph: "कुंजियों के तीरों का उपयोग करें (↑ मुख्य इंजन के लिए, ← और → पार्श्व थ्रस्टरों के लिए) या मोबाइल उपकरणों पर स्क्रीन पर बटन का उपयोग करें। <span class=\"landing-pad\">हरे लैंडिंग पैड</span> पर धीरे से उतरें! हर सफल लैंडिंग आपको अगले स्तर पर ले जाती है। शुरुआती स्तरों में गुरुत्वाकर्षण बढ़ता है और शुरुआती ईंधन कम होता है, जबकि बाद के स्तरों में गुरुत्वाकर्षण स्थिर रहता है लेकिन भूभाग अधिक कठिन हो जाता है.",
    instructions_modal_title: "निर्देश",
    instructions_modal_body: "मॉड्यूल को नियंत्रित करने के लिए तीर कुंजियों का उपयोग करें: ↑ मुख्य इंजन के लिए, ← और → पार्श्व थ्रस्टरों के लिए। मोबाइल उपकरणों पर आप स्क्रीन पर बटन का उपयोग कर सकते हैं। <span class=\"landing-pad\">हरे लैंडिंग पैड</span> पर धीरे से उतरें! हर सफल लैंडिंग आपको अगले स्तर पर ले जाती है। शुरुआती स्तरों में गुरुत्वाकर्षण बढ़ता है और शुरुआती ईंधन कम होता है, जबकि बाद के स्तरों में गुरुत्वाकर्षण स्थिर रहता है लेकिन भूभाग अधिक कठिन हो जाता है.",
    close_instructions: "बंद करें",
    credits_modal_title: "श्रेय",
    credits_modal_body: "यह खेल पूरी तरह से एक बड़े भाषा मॉडल, विशेष रूप से <strong>ChatGPT</strong>, द्वारा उपयोगकर्ता Andrea की ओर से बनाया गया है। सभी कोड और सामग्री एआई द्वारा उपयोगकर्ता की देखरेख में उत्पन्न की गई हैं.",
    close_credits: "बंद करें",
    classic_aria: "क्लासिक लैंडर",
    round_aria: "गोलाकार लैंडर",
    triangle_aria: "त्रिकोणीय लैंडर",
    success_message: "सफल लैंडिंग!",
    crash_message: "दुर्घटना!",
    next_level: "अगला स्तर",
    retry_level: "स्तर दोबारा प्रयास करें"
  }
};

var currentLang = (function() {
  var userLang = (navigator.languages && navigator.languages[0]) ||
                 navigator.language ||
                 navigator.userLanguage;
  if (userLang) {
    userLang = userLang.toLowerCase().split('-')[0];
    if (translations[userLang]) {
      return userLang;
    }
  }
  return 'en';
})();

function setLanguage(lang) {
  currentLang = lang;
  document.documentElement.lang = lang;
  document.documentElement.dir = ['fa', 'ar'].includes(lang) ? 'rtl' : 'ltr';
  var elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    var translation = translations[lang][key];
    if (translation) {
      el.innerHTML = translation;
    }
  });
  var ariaElements = document.querySelectorAll('[data-i18n-aria-label]');
  ariaElements.forEach(function(el) {
    var key = el.getAttribute('data-i18n-aria-label');
    var translation = translations[lang][key];
    if (translation) {
      el.setAttribute('aria-label', translation);
    }
  });
  if (languageSelect) {
    languageSelect.value = lang;
  }
  if (window.game && typeof window.game.updateUI === 'function') {
    window.game.updateUI();
  }
}

var languageSelect = document.getElementById('languageSelect');
if (languageSelect) {
  languageSelect.addEventListener('change', function(e) {
    setLanguage(e.target.value);
  });
}

setLanguage(currentLang);
